language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "dompatchi"
    token:
      secure: "36cd422501eb6750baadf583808cce56bf517c56"

notifications:
  slack: 
    rooms:
    - noseryoungpro-fpp6320:3Ojv3kbMr7yTNRZaxnwds5db#backend
    template:
      - "Code ```%{repository_slug}``` (%{commit}) : %{message}"
      - "Build details: %{build_url}|#%{build_number} on Code```%{branch}``` by %{author} %{result} in %{duration}"

jdk:
  - openjdk11

script:
  - ./gradlew sonarqube