language: java
jdk:
  - openjdk11
  - openjdk-ea

sudo: required

before_install:
 - chmod +x gradlew

script:
  - ./gradlew clean build -i --continue

  matrix:
  allow_failures:
    - jdk: openjdk-ea