language: java
jdk:
  - openjdk11

sudo: false

addons:
  sonarcloud:
    organisation: "dompatchi"
    token:
      secure: ""

before_install:
 - chmod +x gradlew

script:
  - ./gradlew clean build -i --continue
  - ./gradlew sonarqube