language: java
sudo: false
install: true

addons:
  sonarcloud:
    organisation: "Dompatchi"
    token:
      secure: "f1bb3d6d3075b91ec4f6294960f80c06c5508b57"

 jdk:
  - openjdk11

script:
  - ./gradlew sonarqube