language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "dompatchi"
    token:
      secure: "36cd422501eb6750baadf583808cce56bf517c56"

jdk:
  - openjdk11

script:
  - ./gradlew sonarqube

notifications:
  slack: 'Jens Scheidmann:3Ojv3kbMr7yTNRZaxnwds5db#backend'